### ISSUE TITLE
Re: Test results

### ISSUE THREAD

**Issue by smilinazzo** [sloan111/NodeEcosystsm#3]
So, after copying a local version of the events log to the agent/inputs folder so it would run, I ran the suite a few times and with the current implementation, it passed about 40% of the time.

- Would you be concerned that it just results in a flaky test?
- Can you think of a way to adjust the implementation so that its not flaky?

**Comment by sloan111** [comment]
Thank you for bringing this to my attention.  While do not see such a high flake rate on my end, I do not doubt that you did.

>Would you be concerned that it just results in a flaky test?

Of course.  Flaky tests require investigation and maintenance, negating the advantages of automation.  Its basically just manual testing with extra steps.  You want to drive the flake rate as close to zero as possible.

>Can you think of a way to adjust the implementation so that its not flaky?

Happy to dig in to specific fixes, if you'd like to share the error conditions you're seeing.  Otherwise, I'll share my analysis on the flake that I'm seeing here:

When run repeatedly on my end, I do see an error about 10-20% of the time, where a specific event does not appear in the logs.  It appears that in those cases the event logs had not completed being written at the time of retrieval.

This can be trivially solved by adding a sleep to the test code.  A better implementation would be to poll the container list until the Agent finishes execution, then add a buffer sleep before retrieving the event logs.

Ironically, I had a sleep in the code while developing it, but took it out before shipping since it seemed to pass without waiting.  This race condition may vary with system performance, I'm running it on 12core/24 thread processor and hadn't considered performance in more constrained environments.
